-- Supabase 게시글(posts) 테이블 스키마 생성

CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  author text DEFAULT 'Anonymous',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS (Row Level Security) 설정 (원할 경우 주석 해제)
-- ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- 누구나 읽을 수 있는 권한 부여 (Select 정책)
-- CREATE POLICY "Enable read access for all users" ON public.posts FOR SELECT USING (true);

-- 누구나 작성/삭제할 수 있는 임시 권한 (테스트 용도)
-- CREATE POLICY "Enable insert for all users" ON public.posts FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Enable delete for all users" ON public.posts FOR DELETE USING (true);
